"""TS-LOAD and TS-HOOK — profile loading, validation and hook contracts.

Each test names the verification-plan case it implements. The malformed-profile
corpus is generated by mutating the valid MCX profile in exactly one respect, so
every rejection is attributable to that one defect (PLT-VP-R1 §3).
"""

from __future__ import annotations

import copy
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from core import loader, model  # noqa: E402
from core.errors import (  # noqa: E402
    HookContractViolation,
    ProfileLoadError,
    ProfileValidationError,
    StartupRefused,
)
from core.hooks import (  # noqa: E402
    LocationContext,
    MediaKind,
    PriorityDecision,
    Resolution,
    ResolutionKind,
    SessionRequest,
)
from core.validation import build  # noqa: E402
from profiles.common.tables import ResolutionFailure  # noqa: E402

PROFILES = ROOT / "profiles"


# --------------------------------------------------------------------------
# Fixtures
# --------------------------------------------------------------------------


@pytest.fixture(scope="session")
def mcx_raw():
    with (PROFILES / "mcx" / "profile.yaml").open() as fh:
        return yaml.safe_load(fh)


@pytest.fixture
def mutate(mcx_raw):
    """Return a deep copy of the valid profile for one-defect mutation."""
    def _mutate():
        return copy.deepcopy(mcx_raw)
    return _mutate


def expect_defects(raw, *, codes=None, path_contains=None):
    """Validate and assert on the resulting defects."""
    with pytest.raises(ProfileValidationError) as exc:
        build(raw, "test-hash")
    defects = exc.value.defects
    if codes:
        found = set(exc.value.codes())
        assert found & set(codes), f"expected one of {codes}, found {sorted(found)}"
    if path_contains:
        joined = " ".join(exc.value.paths())
        assert path_contains in joined, (
            f"expected a path containing {path_contains!r}, found {exc.value.paths()}")
    return defects


# --------------------------------------------------------------------------
# VP1-LOAD-001, 040, 041 — the valid path
# --------------------------------------------------------------------------


def test_vp1_load_001_valid_profile_loads():
    lp = loader.load(PROFILES / "mcx")
    assert lp.profile.name == "mcx"
    assert lp.profile.version
    assert len(lp.profile.content_hash) == 64
    assert lp.profile.identifier().startswith("mcx/")
    for field in ("identity_resolver", "priority_policy", "session_policy",
                  "bearer_selector", "interworking_gateway"):
        assert getattr(lp.hooks, field) is not None


def test_vp1_load_001_frmcs_profile_loads():
    """The second profile must load against the same code (PLT-VER-001)."""
    lp = loader.load(PROFILES / "frmcs")
    assert lp.profile.name == "frmcs"
    assert lp.profile.functional_identity("train-driver") is not None


def test_vp1_load_040_profile_is_immutable(mcx_raw):
    p = build(copy.deepcopy(mcx_raw), "h")
    with pytest.raises(Exception):
        p.name = "other"                      # frozen dataclass
    with pytest.raises(Exception):
        p.call_types[0].floor.timers_ms["T201"] = 999   # mapping proxy
    with pytest.raises(Exception):
        p.urgencies.append(model.Declared("x", "x"))    # tuple


def test_vp1_load_041_hash_stable_and_sensitive(mutate):
    a = mutate()
    b = mutate()
    assert loader.content_hash(a) == loader.content_hash(b)
    b["profile"]["version"] = "9.9.9"
    assert loader.content_hash(a) != loader.content_hash(b)


def test_vp1_load_041_hash_ignores_key_order(mutate):
    a = mutate()
    b = {k: a[k] for k in reversed(list(a))}
    assert loader.content_hash(a) == loader.content_hash(b)


# --------------------------------------------------------------------------
# VP1-LOAD-010..018 — validation rejections
# --------------------------------------------------------------------------


def test_vp1_load_010_unknown_key_rejected(mutate):
    raw = mutate()
    raw["call_types"][0]["colour"] = "blue"
    expect_defects(raw, codes=["unknown-key"], path_contains="call_types[0].colour")


def test_vp1_load_010_unknown_top_level_key_rejected(mutate):
    raw = mutate()
    raw["experimental"] = {"enabled": True}
    expect_defects(raw, codes=["unknown-key"], path_contains="<root>.experimental")


def test_vp1_load_011_undeclared_urgency_rejected(mutate):
    raw = mutate()
    raw["call_types"][0]["urgency"] = "catastrophic"
    expect_defects(raw, codes=["unresolved-reference"],
                   path_contains="call_types[0].urgency")


def test_vp1_load_012_undeclared_scope_rejected(mutate):
    raw = mutate()
    raw["priority"]["rules"][0]["decision"]["scope"] = "railway"
    expect_defects(raw, codes=["unresolved-reference"],
                   path_contains="priority.rules[0].decision.scope")


def test_vp1_load_013_undeclared_application_rejected(mutate):
    raw = mutate()
    raw["call_types"][0]["application"] = "etcs"
    expect_defects(raw, codes=["unresolved-reference"],
                   path_contains="call_types[0].application")


def test_vp1_load_014_undeclared_initiator_role_rejected(mutate):
    raw = mutate()
    raw["call_types"][0]["initiator_roles"] = ["train-driver"]
    expect_defects(raw, codes=["unresolved-reference"],
                   path_contains="call_types[0].initiator_roles[0]")


def test_vp1_load_015_priority_table_not_total(mutate):
    """Remove the catch-all rule: 'sds' then reaches no decision."""
    raw = mutate()
    raw["priority"]["rules"] = [
        r for r in raw["priority"]["rules"]
        if not (r["match"]["call_type"] == "*" and r["match"]["urgency"] == "*")
    ]
    defects = expect_defects(raw, codes=["not-total"], path_contains="priority.rules")
    assert any("sds" in d.message for d in defects)


def test_vp1_load_016_bearer_table_not_total(mutate):
    raw = mutate()
    raw["bearer"]["rules"] = [
        r for r in raw["bearer"]["rules"] if r["match"]["media"] != "data"
    ]
    defects = expect_defects(raw, codes=["not-total"], path_contains="bearer.rules")
    assert any("data" in d.message for d in defects)


def test_vp1_load_017_reserved_reason_code_rejected(mutate):
    raw = mutate()
    raw["admission"]["reject_reason_codes"].append("hook-timeout")
    expect_defects(raw, codes=["reserved-code"],
                   path_contains="admission.reject_reason_codes")


def test_vp1_load_018_unknown_floor_timer_rejected(mutate):
    raw = mutate()
    raw["call_types"][0]["floor"]["timers_ms"]["T999"] = 100
    expect_defects(raw, codes=["unknown-key"],
                   path_contains="call_types[0].floor.timers_ms.T999")


def test_floor_queueing_inconsistency_rejected(mutate):
    """PLT-ICD-001 §5.3 POST-1/2 — both directions."""
    raw = mutate()
    raw["call_types"][0]["floor"]["queueing_enabled"] = False
    raw["call_types"][0]["floor"]["max_queue_depth"] = 4
    expect_defects(raw, codes=["inconsistent"], path_contains="max_queue_depth")

    raw = mutate()
    raw["call_types"][0]["floor"]["queueing_enabled"] = True
    raw["call_types"][0]["floor"]["max_queue_depth"] = 0
    expect_defects(raw, codes=["inconsistent"], path_contains="max_queue_depth")


def test_bearer_path_consistency_rejected(mutate):
    """PLT-ICD-001 §6.1 POST-1/3 — primary count and redundancy/path agreement."""
    raw = mutate()
    raw["bearer"]["rules"][0]["decision"]["paths"].append(
        {"id": "second", "transport": "udp", "primary": True, "weight": 1,
         "attributes": {}})
    defects = expect_defects(raw, codes=["inconsistent"], path_contains="paths")
    assert any("primary" in d.message for d in defects)


def test_multihomed_requires_two_paths(mutate):
    raw = mutate()
    raw["bearer"]["rules"][0]["decision"]["redundancy"] = "multihomed"
    defects = expect_defects(raw, codes=["inconsistent"])
    assert any("multihomed" in d.message for d in defects)


def test_reserved_capacity_cannot_exceed_maximum(mutate):
    raw = mutate()
    raw["admission"]["max_concurrent_sessions"] = 10
    expect_defects(raw, codes=["inconsistent"],
                   path_contains="admission.reserved_for_urgency")


def test_location_dependent_identity_requires_key(mutate):
    raw = mutate()
    raw["identity"]["functional"] = [{
        "id": "controller", "label": "Controller", "binding": "dynamic",
        "location_dependent": True, "multiplicity": "single", "resolves_to": "user",
    }]
    expect_defects(raw, codes=["inconsistent"], path_contains="location_key")


def test_all_defects_reported_not_just_the_first(mutate):
    """One run must tell the author everything that is wrong."""
    raw = mutate()
    raw["call_types"][0]["urgency"] = "nope"
    raw["call_types"][1]["colour"] = "blue"
    raw["priority"]["rules"][0]["decision"]["scope"] = "nope"
    with pytest.raises(ProfileValidationError) as exc:
        build(raw, "h")
    assert len(exc.value.defects) >= 3


# --------------------------------------------------------------------------
# VP1-LOAD-020..022 — hooks
# --------------------------------------------------------------------------


def test_vp1_load_020_missing_hook_rejected(mutate):
    raw = mutate()
    del raw["profile"]["hooks"]["bearer_selector"]
    expect_defects(raw, codes=["missing-key"],
                   path_contains="profile.hooks.bearer_selector")


def test_vp1_load_021_hook_not_implementing_interface(mutate, tmp_path):
    raw = mutate()
    raw["profile"]["hooks"]["priority_policy"] = "tests.test_loader:BadPolicy"
    profile = build(raw, "h")
    with pytest.raises(ProfileLoadError) as exc:
        loader.resolve_hooks(profile)
    assert "priority_policy" in str(exc.value)
    assert "compare" in str(exc.value)


def test_vp1_load_021_unimportable_hook_module(mutate):
    raw = mutate()
    raw["profile"]["hooks"]["session_policy"] = "no.such.module:Thing"
    profile = build(raw, "h")
    with pytest.raises(ProfileLoadError) as exc:
        loader.resolve_hooks(profile)
    assert "no.such.module" in str(exc.value)


def test_vp1_load_021_bad_hook_specification(mutate):
    raw = mutate()
    raw["profile"]["hooks"]["session_policy"] = "not-a-spec"
    expect_defects(raw, codes=["bad-value"],
                   path_contains="profile.hooks.session_policy")


@pytest.mark.parametrize("field", [
    "identity_resolver", "priority_policy", "session_policy",
    "bearer_selector", "interworking_gateway",
])
def test_vp1_load_022_no_default_hook_substituted(mutate, field):
    """Each hook removed in turn: five refusals, no substitution."""
    raw = mutate()
    del raw["profile"]["hooks"][field]
    expect_defects(raw, codes=["missing-key"],
                   path_contains=f"profile.hooks.{field}")


class BadPolicy:
    """Wrong arity on `compare` — the failure PLT-PRF-013 exists to catch."""

    def __init__(self, profile):
        self.profile = profile

    def evaluate(self, request, resolution):
        raise NotImplementedError

    def compare(self, a):
        raise NotImplementedError


# --------------------------------------------------------------------------
# VP1-LOAD-002..006, 030, 031, 042 — startup rules
# --------------------------------------------------------------------------


def test_vp1_load_002_no_profile_configured():
    with pytest.raises(StartupRefused) as exc:
        loader.startup([], PROFILES, env={})
    assert "no profile configured" in str(exc.value)


def test_vp1_load_003_named_profile_absent():
    with pytest.raises(StartupRefused) as exc:
        loader.startup(["nonexistent"], PROFILES, env={})
    assert "nonexistent" in str(exc.value)


def test_vp1_load_004_two_profiles_refused_outside_test_mode():
    with pytest.raises(StartupRefused) as exc:
        loader.startup(["mcx", "frmcs"], PROFILES, env={})
    assert "exactly one" in str(exc.value)


def test_vp1_load_005_test_mode_refused_in_production():
    env = {"MCX_TEST_MODE": "1", "MCX_ENV": "production"}
    with pytest.raises(StartupRefused) as exc:
        loader.startup(["mcx", "frmcs"], PROFILES, env=env)
    assert "production" in str(exc.value)


def test_vp1_load_005_production_indicator_variants():
    for env in ({"MCX_ENV": "production"}, {"MCX_ENV": "PROD"},
                {"MCX_PRODUCTION": "1"}, {"MCX_PRODUCTION": "true"}):
        assert loader.is_production(env), env
    for env in ({}, {"MCX_ENV": "staging"}, {"MCX_PRODUCTION": "0"}):
        assert not loader.is_production(env), env


def test_vp1_load_006_test_mode_loads_both():
    loaded = loader.startup_all(["mcx", "frmcs"], PROFILES,
                                env={"MCX_TEST_MODE": "1"})
    assert {lp.profile.name for lp in loaded} == {"mcx", "frmcs"}


def test_vp1_load_030_invalid_profile_prevents_start(tmp_path):
    bad = tmp_path / "broken"
    bad.mkdir()
    (bad / "profile.yaml").write_text("profile:\n  name: broken\n")
    with pytest.raises(StartupRefused):
        loader.startup(["broken"], tmp_path, env={})


def test_vp1_load_031_malformed_yaml_reports_clearly(tmp_path):
    bad = tmp_path / "broken"
    bad.mkdir()
    (bad / "profile.yaml").write_text("profile: [unclosed\n")
    with pytest.raises(StartupRefused) as exc:
        loader.startup(["broken"], tmp_path, env={})
    assert "YAML" in str(exc.value) or "well-formed" in str(exc.value)


def test_vp1_load_042_call_type_set_is_profile_determined():
    mcx = loader.load(PROFILES / "mcx").profile
    frmcs = loader.load(PROFILES / "frmcs").profile
    assert mcx.declares_call_type("prearranged-group")
    assert not mcx.declares_call_type("rec-broadcast")
    assert frmcs.declares_call_type("rec-broadcast")
    assert not frmcs.declares_call_type("prearranged-group")


# --------------------------------------------------------------------------
# TS-HOOK — contracts
# --------------------------------------------------------------------------


@pytest.fixture(scope="module")
def mcx():
    return loader.load(PROFILES / "mcx")


@pytest.fixture(scope="module")
def frmcs():
    return loader.load(PROFILES / "frmcs")


def request_for(call_type, target="grp:alpha", initiator="sip:a@mcptt.example",
                media=(MediaKind.VOICE,), **kw):
    return SessionRequest(request_id="r1", initiator=initiator, target=target,
                          call_type=call_type, media=media, **kw)


def test_vp1_hook_020_priority_decision_complete(mcx):
    policy = mcx.hooks.priority_policy
    empty = Resolution(kind=ResolutionKind.GROUP, members=("sip:a@mcptt.example",),
                       group_id="grp:alpha")
    for ct in mcx.profile.call_types:
        d = policy.evaluate(request_for(ct.id), empty)
        assert d.scope in {s.id for s in mcx.profile.preemption_scopes}
        assert d.level >= 0 and d.floor_priority >= 0
        assert d.label


def test_vp1_hook_021_priority_totality(mcx, frmcs):
    for lp in (mcx, frmcs):
        res = Resolution(kind=ResolutionKind.USER, members=("x",))
        for ct in lp.profile.call_types:
            assert lp.hooks.priority_policy.evaluate(request_for(ct.id), res)


def test_vp1_hook_022_cross_scope_comparison_is_zero(mcx, frmcs):
    """The central invariant: no pre-emption across scopes, ever."""
    res = Resolution(kind=ResolutionKind.USER, members=("x",))
    a = mcx.hooks.priority_policy.evaluate(request_for("emergency-group"), res)
    b = frmcs.hooks.priority_policy.evaluate(request_for("rec-broadcast"), res)
    assert a.scope != b.scope
    assert mcx.hooks.priority_policy.compare(a, b) == 0
    assert mcx.hooks.priority_policy.compare(b, a) == 0


def test_vp1_hook_023_comparison_properties(mcx):
    """Antisymmetry, transitivity within a scope, reflexive equality."""
    policy = mcx.hooks.priority_policy
    res = Resolution(kind=ResolutionKind.USER, members=("x",))
    decisions = [policy.evaluate(request_for(ct.id), res)
                 for ct in mcx.profile.call_types]
    for a in decisions:
        assert policy.compare(a, a) == 0
        for b in decisions:
            assert _sign(policy.compare(a, b)) == -_sign(policy.compare(b, a))
            for c in decisions:
                if policy.compare(a, b) > 0 and policy.compare(b, c) > 0:
                    assert policy.compare(a, c) > 0


def _sign(n):
    return (n > 0) - (n < 0)


def test_vp1_hook_024_determinism(mcx):
    policy = mcx.hooks.priority_policy
    res = Resolution(kind=ResolutionKind.USER, members=("x",))
    first = policy.evaluate(request_for("private"), res)
    for _ in range(50):
        assert policy.evaluate(request_for("private"), res) == first


def test_vp1_hook_030_admission_refuses_by_return_value(mcx):
    res = Resolution(kind=ResolutionKind.USER, members=("sip:a@mcptt.example",))
    priority = mcx.hooks.priority_policy.evaluate(request_for("private"), res)
    verdict = mcx.hooks.session_policy.admit(
        request_for("no-such-call-type"), res, priority)
    assert verdict.permitted is False
    assert verdict.reason_code == "call-type-not-permitted"


def test_vp1_hook_031_reason_codes_declared(mcx):
    declared = set(mcx.profile.admission.reject_reason_codes)
    res = Resolution(kind=ResolutionKind.USER, members=("sip:a@mcptt.example",))
    priority = mcx.hooks.priority_policy.evaluate(request_for("private"), res)
    for ct in ("no-such-call-type", "private"):
        verdict = mcx.hooks.session_policy.admit(request_for(ct), res, priority)
        if not verdict.permitted:
            assert verdict.reason_code in declared


def test_admission_enforces_participant_limit(mcx):
    members = tuple(f"sip:u{i}@mcptt.example" for i in range(5))
    res = Resolution(kind=ResolutionKind.GROUP, members=members, group_id="g")
    priority = mcx.hooks.priority_policy.evaluate(request_for("private"), res)
    verdict = mcx.hooks.session_policy.admit(request_for("private"), res, priority)
    assert verdict.permitted is False          # private call caps at 2
    assert verdict.reason_code == "capacity-exhausted"


def test_admission_enforces_capacity(mcx):
    res = Resolution(kind=ResolutionKind.USER, members=("sip:a@mcptt.example",))
    priority = mcx.hooks.priority_policy.evaluate(request_for("private"), res)
    req = request_for("private", attributes={"core.active_sessions": "2000"})
    verdict = mcx.hooks.session_policy.admit(req, res, priority)
    assert verdict.permitted is False
    assert verdict.reason_code == "capacity-exhausted"


def test_vp1_hook_033_session_decision_applied_verbatim(mcx):
    res = Resolution(kind=ResolutionKind.GROUP, members=("x",), group_id="g")
    decision = mcx.hooks.session_policy.decide(request_for("emergency-group"), res)
    declared = mcx.profile.call_type("emergency-group")
    assert decision.auto_answer == declared.auto_answer
    assert decision.acknowledgement_required == declared.acknowledgement_required
    assert decision.recording_required == declared.recording_required
    assert decision.max_participants == declared.max_participants


def test_vp1_hook_034_floor_policy_matches_profile(mcx):
    res = Resolution(kind=ResolutionKind.GROUP, members=("x",), group_id="g")
    fp = mcx.hooks.session_policy.floor_policy(
        request_for("emergency-group"), res)
    assert fp.queueing_enabled is False and fp.max_queue_depth == 0
    assert fp.timers_ms["T2"] == 2000


def test_vp1_hook_040_bearer_decision_well_formed(mcx, frmcs):
    for lp in (mcx, frmcs):
        res = Resolution(kind=ResolutionKind.USER, members=("x",))
        for ct in lp.profile.call_types:
            media = tuple(MediaKind(m) for m in ct.media)
            priority = lp.hooks.priority_policy.evaluate(request_for(ct.id), res)
            d = lp.hooks.bearer_selector.select(request_for(ct.id), priority, media)
            assert sum(1 for p in d.paths if p.primary) == 1
            assert len({p.path_id for p in d.paths}) == len(d.paths)
            if d.redundancy == "single":
                assert len(d.paths) == 1
            else:
                assert len(d.paths) >= 2


def test_vp1_hook_041_arp_consistency_violation(mcx):
    """A bearer rule may not request more pre-emption than priority authorises."""
    selector = mcx.hooks.bearer_selector
    weak = PriorityDecision(level=1, scope="public-safety",
                            preemption_capability=False,
                            preemption_vulnerability=True,
                            floor_priority=1, label="weak")
    with pytest.raises(HookContractViolation):
        selector.select(request_for("emergency-group"), weak, (MediaKind.VOICE,))


def test_bearer_path_event_returns_none_for_unknown_event(mcx):
    assert mcx.hooks.bearer_selector.on_path_event("s1", {"type": "nonsense"}) is None


# --------------------------------------------------------------------------
# TS-HOOK — identity resolution
# --------------------------------------------------------------------------


def test_vp1_hook_010_resolution_kinds(mcx):
    r = mcx.hooks.identity_resolver
    r.register_user("sip:a@mcptt.example")
    r.register_group("grp:alpha", ["sip:a@mcptt.example", "sip:b@mcptt.example"])
    r.register_user("sip:b@mcptt.example")

    user = r.resolve("sip:a@mcptt.example", request_for("private"))
    assert user.kind is ResolutionKind.USER and len(user.members) == 1

    group = r.resolve("grp:alpha", request_for("prearranged-group"))
    assert group.kind is ResolutionKind.GROUP and group.group_id == "grp:alpha"
    assert len(group.members) == 2

    with pytest.raises(ResolutionFailure) as exc:
        r.resolve("sip:nobody@mcptt.example", request_for("private"))
    assert exc.value.reason_code == "unknown-target"


def test_vp1_hook_011_members_deduplicated_and_ordered(mcx):
    r = mcx.hooks.identity_resolver
    r.register_group("grp:dupes", ["sip:a@mcptt.example", "sip:b@mcptt.example",
                                   "sip:a@mcptt.example"])
    first = r.resolve("grp:dupes", request_for("prearranged-group")).members
    assert first == ("sip:a@mcptt.example", "sip:b@mcptt.example")
    for _ in range(5):
        assert r.resolve("grp:dupes", request_for("prearranged-group")).members == first


def test_vp1_hook_012_domain_restriction(mcx):
    """PLT-IDM-008 — nothing resolves outside the profile's declared domains."""
    r = mcx.hooks.identity_resolver
    with pytest.raises(ResolutionFailure) as exc:
        r.register_user("sip:intruder@frmcs.example")
    assert exc.value.reason_code == "not-authorised"


def test_vp1_hook_013_resolved_from_recorded(frmcs):
    r = frmcs.hooks.identity_resolver
    r.bind("train-driver", "sip:driver1@frmcs.example", None)
    res = r.resolve("train-driver", request_for("driver-controller",
                                                target="train-driver"))
    assert res.resolved_from == "train-driver"
    assert res.members == ("sip:driver1@frmcs.example",)


def test_vp1_hook_015_resolution_failure_codes_distinct(frmcs):
    """An unheld role and a nonexistent role are different conditions."""
    r = frmcs.hooks.identity_resolver
    req = request_for("driver-controller", target="track-controller",
                      initiator="sip:x@frmcs.example",
                      location=LocationContext(attributes={"track_section": "S1"}))
    with pytest.raises(ResolutionFailure) as unheld:
        r.resolve("track-controller", req)
    assert unheld.value.reason_code == "no-binding"

    with pytest.raises(ResolutionFailure) as unknown:
        r.resolve("sip:ghost@frmcs.example", req)
    assert unknown.value.reason_code == "unknown-target"


def test_location_dependent_resolution(frmcs):
    r = frmcs.hooks.identity_resolver
    s1 = LocationContext(attributes={"track_section": "S1"})
    s2 = LocationContext(attributes={"track_section": "S2"})
    r.bind("track-controller", "sip:ctrl1@frmcs.example", s1)
    r.bind("track-controller", "sip:ctrl2@frmcs.example", s2)

    req1 = request_for("driver-controller", target="track-controller", location=s1)
    req2 = request_for("driver-controller", target="track-controller", location=s2)
    assert r.resolve("track-controller", req1).members == ("sip:ctrl1@frmcs.example",)
    assert r.resolve("track-controller", req2).members == ("sip:ctrl2@frmcs.example",)

    nowhere = request_for("driver-controller", target="track-controller")
    with pytest.raises(ResolutionFailure) as exc:
        r.resolve("track-controller", nowhere)
    assert exc.value.reason_code == "no-location-binding"


def test_single_holder_binding_replaces(frmcs):
    """ICD-OP-02: provisional choice, asserted so a change of mind is visible."""
    r = frmcs.hooks.identity_resolver
    r.bind("train-driver", "sip:d1@frmcs.example", None)
    r.bind("train-driver", "sip:d2@frmcs.example", None)
    res = r.resolve("train-driver", request_for("driver-controller",
                                                target="train-driver"))
    assert res.members == ("sip:d2@frmcs.example",)


def test_unbinding_nothing_is_a_noop(frmcs):
    frmcs.hooks.identity_resolver.unbind("train-driver", "sip:never@frmcs.example")


def test_mcx_resolver_declares_no_functional_identities(mcx):
    with pytest.raises(ResolutionFailure):
        mcx.hooks.identity_resolver.bind("anything", "sip:a@mcptt.example", None)
    assert mcx.hooks.identity_resolver.identities_of("sip:a@mcptt.example") == ()


# --------------------------------------------------------------------------
# TS-HOOK — interworking
# --------------------------------------------------------------------------


def test_vp1_hook_050_route_matches_prefix(mcx):
    res = Resolution(kind=ResolutionKind.USER, members=("x",))
    route = mcx.hooks.interworking_gateway.route(
        request_for("private", target="tetra:1234"), res)
    assert route is not None and route.system == "tetra"
    assert mcx.hooks.interworking_gateway.route(
        request_for("private", target="sip:a@mcptt.example"), res) is None


def test_vp1_hook_051_inbound_mapping_rejects_undeclared(mcx):
    with pytest.raises(HookContractViolation):
        mcx.hooks.interworking_gateway.map_inbound(
            {"call_type": "rec-broadcast", "initiator": "sip:a@mcptt.example"})
    with pytest.raises(HookContractViolation):
        mcx.hooks.interworking_gateway.map_inbound(
            {"call_type": "private", "initiator": "sip:a@elsewhere.example"})


def test_inbound_mapping_builds_valid_request(mcx):
    req = mcx.hooks.interworking_gateway.map_inbound({
        "call_type": "private", "initiator": "sip:a@mcptt.example",
        "target": "sip:b@mcptt.example", "system": "tetra"})
    assert req.call_type == "private"
    assert req.media == (MediaKind.VOICE,)


# -- PLT-CONF-AUDIT CA-15: 5QI and ARP -----------------------------------------


def test_standardised_5qi_values_match_the_specification():
    """TS 23.501 table 5.7.4-1, identical in Rel-17 and Rel-19.

    Spelled out rather than imported, so the table and the assertion cannot
    drift together (PLT-CONF-AUDIT 4.10).
    """
    from core.qos import STANDARDISED_5QI
    assert STANDARDISED_5QI == {
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76,
        79, 80, 82, 83, 84, 85, 86, 87, 88, 89, 90,
    }


def test_mission_critical_5qis_carry_the_media_they_were_defined_for():
    """The five MC values, from table 5.7.4-1's Example Services column.
    67 is video, which is the whole point of CA-15."""
    from core.qos import media_of
    assert media_of(65) == "voice"      # MC user plane Push To Talk voice
    assert media_of(66) == "voice"      # Non-MC user plane Push To Talk voice
    assert media_of(67) == "video"      # MC Video user plane
    assert media_of(69) == "data"       # MC delay sensitive signalling
    assert media_of(70) == "data"       # MC Data
    assert media_of(9) is None and media_of(1) is None


def test_a_bearer_rule_may_not_request_a_5qi_defined_for_other_media(mutate):
    """The defect CA-15 found in an in-tree profile: a data bearer asking for
    the Mission Critical Video 5QI. Accepted silently before, because
    `qos_identifier` was never validated at all."""
    raw = mutate()
    rule = next(r for r in raw["bearer"]["rules"] if r["match"]["media"] == "data")
    rule["decision"]["qos_identifier"] = 67
    expect_defects(raw, codes=("inconsistent",),
                   path_contains="decision.qos_identifier")


def test_a_voice_rule_may_not_request_the_data_5qi(mutate):
    """The same check in the other direction, so it cannot pass by only ever
    looking at one media kind."""
    raw = mutate()
    rule = next(r for r in raw["bearer"]["rules"] if r["match"]["media"] == "voice")
    rule["decision"]["qos_identifier"] = 70
    expect_defects(raw, codes=("inconsistent",))


def test_an_operator_specific_5qi_is_accepted_and_not_cross_checked(mutate):
    """TS 23.501 clause 5.7.3 allows pre-configured, non-standardised 5QIs.
    Their characteristics are not knowable here, so they must not be refused:
    a validator that accepted only the standardised table would reject a
    legitimate deployment."""
    raw = mutate()
    for rule in raw["bearer"]["rules"]:
        rule["decision"]["qos_identifier"] = 140
    build(raw, "test-hash")        # must not raise


@pytest.mark.parametrize("arp", [0, 16, 99])
def test_arp_outside_1_to_15_is_refused(mutate, arp):
    """TS 23.501 clause 5.7.2.2: "The range of the ARP priority level is 1 to
    15 with 1 as the highest priority." The range was already enforced; CA-15
    is the first time it was read from the specification rather than assumed.
    """
    raw = mutate()
    raw["bearer"]["rules"][0]["decision"]["arp_level"] = arp
    expect_defects(raw, path_contains="arp_level")
